name: pi-gen-action
description: Build a custom Raspberry Pi image

inputs:
  # pi-gen variables

  pi-gen-version:
    description: Release version of pi-gen to use
    required: false
    # Currently, theres a bug in pi-gen if building for 64bit targets: https://github.com/RPi-Distro/pi-gen/issues/271
    # We assume this is mostly the case, so this is set to the fix in the branch by default
    default: arm64
  enable-noobs:
    description: Set whether a noobs image should be built as well
    required: false
    default: false
  use-qcow2:
    description: Use qcow2 images to reduce space and runtime requirements
    required: false
    default: 1
  stage-list:
    description: List of stage name to execute in given order. Relative and absolute paths to custom stage directories are allowed here.
    required: false
    default: 'stage0 stage1 stage2'
  image-name:
    description: Final image name
    required: true
  release:
    description: The release version to build images against. Valid values are jessie, stretch, buster, bullseye, and testing
    required: false
    default: bullseye
  compression:
    description: Compression to apply on final image (either "none", "zip", "xz" or "gz")
    required: false
    default: zip
  compression-level:
    description: Compression level to be used. From 0 to 9 (refer to the tool man page for more information on this. Usually 0 is no compression but very fast, up to 9 with the best compression but very slow).
    required: false
    default: 6
  locale:
    description: Default locale of the system image
    required: false
    default: en_GB.UTF-8
  hostname:
    description: Host name of the image
    required: false
    default: raspberrypi
  keyboard-keymap:
    description: Default keyboard keymap
    required: false
    default: gb
  keyboard-layout:
    description: Default keyboard layout
    required: false
    default: English (UK)
  timezone:
    description: System timezone
    required: false
    default: Europe/London
  username:
    description: Name of the initial user account
    required: false
    default: pi
  password:
    description: Password of the intial user account, locked if empty
    required: false
  wpa-essid:
    description: SSID of a default wifi network to connect to
    required: false
  wpa-password:
    description: Password of default wifi network to connect to
    required: false
  wpa-country:
    description: Wifi country code of default network to connect to
    required: false
  enable-ssh:
    description: Enable SSH access to Pi
    required: false
    default: 0

  # action variables
  pi-gen-dir:
    description: Temporary directory where to run pi-gen in container
    required: false
    default: pi-gen
  verbose-output:
    description: Print all output from pi-gen
    required: false
    default: false
  github-token:
    description: Token to use for checking out pi-gen repo
    required: false
    default: ${{ github.token }}

outputs:
  image-path:
    description: Path to the final custom image
    value: 
  image-noobs-path:
    description: Path to final noobs image, if enabled
    value: 

runs:
  using: node16
  main: dist/index.js
