name: Run pi-gen
on: push

jobs:
  pi-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'RPi-Distro/pi-gen'
          ref: 'arm64'
          path: 'pi-gen'

      - run: sudo apt-get install $(grep -Po '[^:]+$' pi-gen/depends)

      - run: >
          echo -e "IMG_NAME='pi-gen-action-test'\nUSE_QCOW2=1\nDEPLOY_COMPRESSION=xz" > config &&
          touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES &&
          sudo ./build.sh
        working-directory: pi-gen
