name: Run pi-gen
on: 
  workflow_dispatch:

jobs:
  pi-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: >
          mkdir -p test-stage/package-test && 
          echo -e "#!/bin/bash\napt-get install -y curl\ncurl -fsSL https://deb.nodesource.com/setup_16.x | bash -" > test-stage/package-test/00-run-chroot.sh &&
          chmod +x test-stage/package-test/00-run-chroot.sh &&
          echo "nodejs" > test-stage/package-test/01-packages && 
          echo -e "#!/bin/bash -e\nif [ ! -d \"\${ROOTFS_DIR}\" ]; then\n  copy_previous\nfi" > test-stage/prerun.sh &&
          chmod +x test-stage/prerun.sh

      - uses: ./
        id: build
        with:
          image-name: test
          stage-list: stage0 stage1 stage2 test-stage
          verbose-output: true
          enable-noobs: true
          compression: xz
          compression-level: 9
          locale: de_DE.UTF-8
          hostname: pi-gen-test
          keyboard-keymap: de
          keyboard-layout: German - no dead keys
          username: pi-gen
          wpa-essid: foo
          wpa-password: '1234567890'

          # System timezone.
          timezone: Europe/London

      - run: tree 
      
      - uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}
          retention-days: 2
      
      - uses: actions/upload-artifact@v3
        with:
          name: pi-gen-noobs-image
          path: ${{ steps.build.outputs.image-noobs-path }}
          retention-days: 2

