name: Shellcheck
on: push

jobs:
  pi-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run shellcheck
        uses: sudo-bot/action-shellcheck@latest
        with:
          # https://github.com/koalaman/shellcheck#how-to-use
          cli-args: "--format=checkstyle --severity=info **/*.sh"
